name: C# Syntax Check CI

on: [push, pull_request]

jobs:
  proverka:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore
      run: dotnet restore

    - name: Install FxCopAnalyzers
      run: dotnet add Api_Smart_Counters/Api_Smart_Counters.csproj package Microsoft.CodeAnalysis.FxCopAnalyzers

    - name: Build with FxCopAnalyzers
      run: dotnet build --no-restore -c Release
